use_frameworks!

platform :ios, '8.0'

target 'SharkerQRViewController_Example' do
  pod 'SharkerQRViewController', :path => '../'

  target 'SharkerQRViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
